public class Calculator {
    integer a=20;
    integer b=10;
    integer result;
    public void add(){
        result=a+b;
        system.debug('Sum is = '+result);
    }
    public void sub(){
        result=a-b;
        system.debug('Sub is = '+result);
    }
    public void mul(){
        result=a*b;
        system.debug('mul is = '+result);
    }
    public void div(){
        result=a/b;
        system.debug('div is = '+result);
    }
    

}