public with sharing class OTMMEndpoints {
    public OTMMEndpoints() {

    }
    public static final String assets = '/assets';
    public static final String  assetState= '/assets/state';
    public static final String  importJob ='/jobs/imports';
    public static final String  renditions = '/renditions/';
    public static final string  JobCheckIn = '/jobs/checkins/';
    public static final string  userPreference = '/preferences';
    public static final string metadatamodels='/metadatamodels/';
    public static final string folders='/folders/';
    public static final string children='/children';
   

    public static final String  assetsValue= '/assets/';
    public static final String  state= '/state';

}