name: CodeTour watch

on:
    pull_request:
        types: [opened, edited, synchronize, reopened]

jobs:
    codetour-watch:
        runs-on: trailheadapps-Ubuntu
        steps:
            - name: 'Checkout source code'
              uses: actions/checkout@v3

            - name: 'Watch CodeTour changes'
              uses: pozil/codetour-watch@v1.6.3
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
